services:
  bluepanel:
    build:
      context: .
      dockerfile: Dockerfile
    image: bluepanel:local
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/bluepanel:/var/lib/bluepanel
